GET http://localhost:3333/pokemon
###
GET http://localhost:3333/pokemon/3

###
POST http://localhost:3333/pokemon
Content-Type: application/json

{
    "name": "charmander"
}
###
PATCH http://localhost:3333/pokemon/3
Content-Type: application/json

{
    "name": "charmander"
}
###
DELETE http://localhost:3333/pokemon/4